config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  
  resources :contests
  
  get 'signup', to: 'users#new'
  resources :users, except: [:new]

end
Rails.application.routes.draw do

end

app/models/contest.rb
class Contest < ActiveRecord::Base
    belongs_to :user
  
    validates :title, presence: true, length: {minimum: 3, maximum: 50}
    validates :description, presence: true, length:{ minimum: 10, maximum: 300}
    validates :categories, presence: true, length:{ minimum: 1, maximum: 300}
    validates :locations, presence: true, length:{ minimum: 1, maximum: 300}
    validate :end_date_greater_than_start_date
    
    validates :user_id, presence: true

    def end_date_greater_than_start_date
      if !end_date.blank? and end_date.to_date < start_date.to_date
        errors.add(:end_date, "should be greater than start date")
      end
    end
end       

app/models/user.rb
class User < ActiveRecord::Base
    has_many :contests
    
    before_save { self.email = email.downcase }
    validates :username, presence: true,
    uniqueness: { case_sensitive: false }, 
        length: { minimum: 3, maximum: 25 }
    VALID_EMAIL_REGEX = /([A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4})/i    
    validates :email, presence: true, length: { maximum: 105 },
        uniqueness: { case_sensitive: false },
        format: { with: VALID_EMAIL_REGEX }
        
    has_secure_password    
end    

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
    def index
        @contests = Contest.all    
    end
    
    def new
        @contest = Contest.new
    end
    
    def edit
       @contest = Contest.find(params[:id]) 
    end    
    
    def create
        @contest = Contest.new(contest_params)
        @contest.user = User.first
        if @contest.save
            flash[:success] = "Contest successfully created"
           redirect_to contest_path(@contest) 
        else
            render 'new' 
        end 
    end
    
    def update
        @contest = Contest.find(params[:id])
        if @contest.update(contest_params)
            flash[:success] = "Contest succesfully updated"
            redirect_to contest_path(@contest)
        else
            render 'edit'
        end    
    end    
        def contest_params
            params.require(:contest).permit(:title, :categories, :start, :end, :description, :locations, :terms_and_conditions)
        end
    
    def show
      @contest = Contest.find(params[:id])  
    end  
    
    def destroy
        @contest = Contest.find(params[:id]).destroy
        @contest.destroy
        flash[:danger] = "Contest successfully deleted"
        redirect_to contests_path
    end    
    
    private
        def contest_params
            params.require(:contest).permit(:title, :categories, :start, :end, :description, :locations, :terms_and_conditions)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    
    end       
end    

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all    
    end
    
    def new
        @user = User.new
    end      
    
    def create
        @user = User.new(user_params)
        if @user.save
            flash[:success] = "Welcome to the giveaway #{@user.username}"
            redirect_to contests_path
        else
           render 'new' 
        end    
    end    
    
    def edit
       @user = User.find(params[:id])     
    end
    
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:success] = "Your accound was updated succesfully"
            redirect_to contests_path
        else
            render 'edit'
        end    
    end    
    
    def show
       @user = User.find(params[:id]) 
    end    
    
    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end    
end     

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, option = {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase) 
        size = option[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
    end    
end

app/views/contests/_contest.html.erb
    <% obj.each do |contest| %>
        <div class="container">
            <div class="jumbotron col-xs-8 col-xs-offset-2"> 
                <div class = "contest-title">
                    <%= link_to contest.title, contest_path(contest) %>
                </div>
                <div class= "contest-body">
                    <%= truncate(contest.description, length:100) %><br>    
                    <%= contest.categories %>
                    <%= contest.start_date %>
                    <%= contest.end_date %> <br>
                    <%= contest.locations %><br>
                    <div class="contest-meta-details"><small>
                        Created by: <%= contest.user.username if contest.user  %>
                        <%= time_ago_in_words(contest.created_at) %> ago,
                        Last updated: <%= time_ago_in_words(contest.updated_at)%> ago
                    </small></div>
                </div>
                <div class="contest_actions">
                  <%= link_to "Edit This contest", edit_contest_path(contest), class: "btn btn-xs btn-primary" %>
                  <%= link_to "Delete This contest", contest_path(contest), 
                      method: :delete,
                      data: { comfirm: "Are you sure you want to delete the contest?"}, 
                      class: "btn btn-xs btn-danger" %>
                </div>
            </div>
        </div>    
    <% end %>    

app/views/contests/_form.html.erb
<div class= "register-photo"> 
<%= render 'shared/errors', obj: @contest %>
    <div class="form-container"> 
    <%= form_for @contest do |f| %>
        
             <h1 class="text-center"> <strong>Create</strong> an Contest </h1>
             <div class="form-group">
                <%= f.text_field :title, class: "form-control", placeholder: "Title fo contest" %>
             </div>
             <div class="form-group">
                <%= f.text_field :categories, class: "form-control", placeholder: "Category Of contest" %>
             </div>
             <div class="row">
                 <div class="col-md-6 form-group"><%= f.date_field :start_date,  class: "form-control", placeholder: "Start Date:" %></div>
                 <div class="col-md-6 form-group"><%= f.date_field :end_date,  class: "form-control", placeholder: "End Date:" %></div>
             </div>
             <div class="form-group">
                <%= f.text_field :locations, class: "form-control", placeholder: "Contest Available for locations" %>
             </div>             
            <div class="form-group">
                <%= f.text_area :description, class: "form-control", placeholder: "Description of Contest" %>
            </div>
            <div class="form-group">
            <label class="form-control">Terms and Conditions(PDF Only):    
                <%= f.file_field :terms_and_conditions, accept: 'application/pdf' %></label>
             </div>  
            <div class="row">
                
                <%= f.submit  class: "btn btn-primary btn-block"%>
            </div>
            </div>
        </div>    
    <% end %>
    
    <%= link_to "Back to contests listing", contests_path%>
</div>

app/views/contests/edit.html.erb
<%= render 'form' %>

app/views/contests/index.html.erb
<h1 align="center">All Contests</h1>
<%= render 'contest', obj: @contests %>



   

app/views/contests/new.html.erb
<%= render 'form' %>

app/views/contests/show.html.erb
    <div class="container">    
        <h2 class="display-4" align="center"><%= @contest.title %></h2>
        <div class="jumbotron">
        <ul class="listing">
            <div class="row">
                <div class="col-md-12" align="center">
                    <li><%= link_to gravatar_for(@contest.user), user_path(@contest.user)%></li>
                    <li class="contest-title">
                        <% link_to @contest.user.username, user_path(@contest.user) %>
                    </li>
                    <li><small><%= pluralize(@contest.user.contests.count, "contest") if @contest.user.contests %></small></li>
                </div>
            </div>    
        </ul>
        
        <h4 class="center"><strong>Description:-</strong></h4>  
          
            <%= simple_format(@contest.description) %><hr>
            
        <p>Category:-  <%= @contest.categories %></p><hr>
        <p>Start Date:-  <%= @contest.start_date %></p><hr>
        <p>End Date:-  <%= @contest.end_date %></p>   <hr>
        <p>Locations:-  <%= @contest.locations %></p><hr>
        <p>Image name:-  <%= @contest.terms_and_conditions %></p><hr>
    
    
        <div class="contest_actions">
          <%= link_to "Edit This contest", edit_contest_path(@contest), class: "btn btn-xs btn-primary" %>
          <%= link_to "Delete This contest", contest_path(@contest), 
              method: :delete,
              data: { comfirm: "Are you sure you want to delete the contest?"}, 
              class: "btn btn-xs btn-danger" %>
          <%= link_to "View all contests", contests_path, class: "btn btn-xs btn-success" %>    
        </div>
    </div> 
    </div>


  

app/views/layouts/_footer.html.erb
<!--Footer Start-->
<div class="footer-dark">
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-3 item">
                    <h3>Services</h3>
                    <ul>
                        <li><a href="#">Web design</a></li>
                        <li><a href="#">Development</a></li>
                        <li><a href="#">Hosting</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-md-3 item">
                    <h3>About</h3>
                    <ul>
	                        <li><a href="#">Company</a></li>
                        <li><a href="#">Team</a></li>
                        <li><a href="#">Careers</a></li>
                    </ul>
                </div>
                <div class="col-md-6 item text">
                    <h3>Company Name</h3>
                    <p>Praesent sed lobortis mi. Suspendisse vel placerat ligula. Vivamus ac sem lacus. Ut vehicula rhoncus elementum. Etiam quis tristique lectus. Aliquam in arcu eget velit pulvinar dictum vel in justo.</p>
                </div>
                <div class="col item social">
                	<a href="#">
                		<i class="fa fa-facebook"></i>
                	</a>
                	<a href="#">
                		<i class="fa fa-twitter-square"></i>
                	</a>
                	<a href="#">
                		<i class="fa fa-snapchat"></i>
                	</a>
                	<a href="#">
                		<i class="fa fa-instagram"></i>
                	</a>
                </div>
            </div>
            <p class="copyright">Company Name © 2017</p>
        </div>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<div class = "container">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}"%>'>
          <a href="#" class="close" data-dismiss="alert">&#215;</a>
          <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
</div>  

app/views/layouts/_navigation.html.erb
    <nav class="navbar navbar-light navbar-expand-md navigation-clean-button" style="background-color:rgb(13,242,215);color:rgb(3,3,3);">
        <div class="container">
            
        	<%= link_to "Giveaway", root_path, class: "navbar-brand"%>
        	<button class="navbar-toggler" data-toggle="collapse" data-target="#navcol-1">
        		<span class="sr-only">Toggle navigation</span>
        		<span class="navbar-toggler-icon"></span>
        	</button>
        	
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item" role="presentation"><a class="nav-link" href="/">Home</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="contests">Contests</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="contests/new">New Contests</a></li>
                </ul>
                
                <span class="navbar-text actions">
                	<a href="/" class="login">Log In</a>
                	<a class="btn btn-light action-button" role="button" href="signup">Sign Up</a>
                </span>
                
            </div>
            
        </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'layouts/navigation'  %>
  <%= render 'layouts/messages'  %>

    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
<%= render 'layouts/footer'  %>


</body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron">
    <h1>Welcome to giveaway</h1>
    <%= link_to "Sign up now", "signup", class: "btn btn-primary btn-lg" %>
</div>

app/views/shared/_errors.html.erb
 <div class="container ">      
    <% if obj.errors.any? %>
        <div class = "row">
            <div class ="form-container">
                <div class="alert alert-danger">
                    <div class = "alert-heading"> 
                        <h2 class="alert-title">
                            <%= pluralize(obj.errors.count, "error") %>
                                probhited this article from being saved:
                        </h2> 
                        <div class= "contest-body">
                            <ul>
                                <% obj.errors.full_messages.each do |msg| %>
                                    <li><%= msg %></li>
                                <% end %>
                            </ul>
                        </div>    
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/users/edit.html.erb
<div class= "register-photo"> 
    <%= render 'shared/errors', obj: @user %>
        <div class="form-container">
            <div class="image-holder"></div> 
            <%= form_for @user do |f| %>     
                     <h2 class="text-center"> <strong>Edit</strong> your Account </h2>
                     <div class="form-group">
                        <%= f.text_field :username, class: "form-control", placeholder: "Enter Username" %>
                     </div>
                     <div class="form-group">
                        <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
                     </div>
                     <div class="form-group">
                        <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
                     </div>             
                    <div class="row">
                   
                        <%= f.submit "Update your account",  class: "btn btn-primary btn-block"%>
                    </div>
                    </div>
                </div>    
            <% end %>
        </div>    
</div>

app/views/users/index.html.erb
<h1 align="center">All Contests Users</h1>
<div class="container">
    <% @users.each do |user| %>
        <ul class="listing" align="center">
            <div class="row" align="center">
                <div class="jumbotron col-md-12 ">
                    <li><%= link_to gravatar_for(user), user_path(user) %></li>
                    <li class="contest-title">
                        <%= link_to user.username, user_path(user) %>
                    </li>
                    <li><small><%= pluralize(user.contests.count, "contest") if user.contests %></small></li>
                </div>
            </div>    
        </ul>
    <% end %>
</div>    

app/views/users/new.html.erb
<div class= "register-photo"> 
        <div class="form-container">
            <div class="image-holder"></div> 
            <%= form_for @user do |f| %>     
                     <h2 class="text-center"> <strong>Create</strong> an Account </h2>
                     <div class="form-group">
                        <%= f.text_field :username, class: "form-control", placeholder: "Enter Username" %>
                     </div>
                     <div class="form-group">
                        <%= f.email_field :email, class: "form-control", placeholder: "Enter email" %>
                     </div>
                     <div class="form-group">
                        <%= f.password_field :password, class: "form-control", placeholder: "Enter password" %>
                     </div>             
                    <div class="row">
                   
                        <%= f.submit "Sign Up",  class: "btn btn-primary btn-block"%>
                    </div>
                    </div>
                </div>    
            <% end %>
        </div>    
</div>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>
<div class= "row">
    <div class="col-md-12" align = "center">
        <%= gravatar_for @user, size: 150 %>
    </div>
</div> 

<h4 align="center"><%= @user.username %>'s contests</h4>
<%= render 'contests/contest', obj: @user.contests %>